name: "Valida role ansible"
  
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  valida:
    uses: "williamsanmartin4/cicd_centralizado/.github/workflows/docker_build.yaml@pipeline_docker"
    with:
      tag: "latest"
