name: "Valida role ansible"
  
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  valida:
    uses: "williamsanmartin4/cicd_centralizado/.github/workflows/docker_build.yaml@ddb9297e45946de3a0b9b73d5df64a94a71010af"
    with:
      tag: "latest"

